Fix a missing null check
https://pipelines.actions.githubusercontent.com/7Gj3MhcqWfw2g5AJ4hFloDPqGYajpJOTzWC0tmc6o1ZS1jre7w/_apis/pipelines/1/runs/200/signedlogcontent/9?urlExpires=2020-03-16T18%3A41%3A53.3257016Z&urlSigningMethod=HMACV1&urlSignature=Y4egBzpzR0375m1EKEuUK29qjZX5BlpNwDFL69e49I0%3D

```
2020-03-15T00:17:31.8696670Z Executing cmd: devices
2020-03-15T00:17:31.8697000Z Result is "Serial ID: None
2020-03-15T00:17:31.8697330Z Manufacturer: unknown
2020-03-15T00:17:31.8697670Z Model: Android SDK built for x86_64 (Android SDK built for x86_64)
2020-03-15T00:17:31.8698000Z Release: 8.0.0
2020-03-15T00:17:31.8698320Z SDK version: 26
2020-03-15T00:17:31.8698750Z CPU: x86_64"
2020-03-15T00:17:31.8699280Z Executing cmd: dont-keep-activities on
2020-03-15T00:17:31.8700150Z Result is ""
2020-03-15T00:17:31.8700500Z Stderr is "Traceback (most recent call last):
2020-03-15T00:17:31.8701290Z   File "/Users/runner/runners/2.165.2/work/adb-enhanced/adb-enhanced/tests/../src/main.py", line 385, in <module>
2020-03-15T00:17:31.8701720Z     main()
2020-03-15T00:17:31.8702490Z   File "/Users/runner/runners/2.165.2/work/adb-enhanced/adb-enhanced/tests/../src/main.py", line 217, in main
2020-03-15T00:17:31.8702910Z     new_state = adb_enhanced.get_dont_keep_activities_in_background_state()
2020-03-15T00:17:31.8703720Z   File "/Users/runner/runners/2.165.2/work/adb-enhanced/adb-enhanced/src/adb_enhanced.py", line 633, in get_dont_keep_activities_in_background_state
2020-03-15T00:17:31.8704500Z     if stdout.strip() == 'null':
2020-03-15T00:17:31.8705270Z AttributeError: 'NoneType' object has no attribute 'strip'"
```